version: "3"
services:
  postgresql-primary:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always
    volumes:
      - /var/lib/postgresql-primary/data:/var/lib/postgresql/data
    networks:
      - postgresql-primary-backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  postgresql-primary-backend:
    external: true
