version: "3"
services:
  postgresql-primary:
    container_name: postgresql-primary
    image: postgres:14-alpine
    environment:
      # Required for passing runtime env vars with Portainer. Known bug. https://github.com/portainer/portainer/issues/5016#issuecomment-828101692
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always
    volumes:
      - /var/lib/postgresql-primary/data:/var/lib/postgresql/data
    networks:
      - postgresql-primary-backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  postgresql-primary-backend:
    name: postgresql-primary-backend
    driver: bridge
    ipam:
      config:
        - subnet: "${SUBNET}"
    driver_opts:
      com.docker.network.bridge.name: postgresql0
