version: "3"
services:
  postgresql-primary:
    image: postgres:alpine
    logging:
      driver: "none"
    restart: always
    volumes:
      - /var/lib/postgresql-primary/data:/var/lib/postgresql/data
    networks:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  backend:
    external: true
