version: "3"
services:
  postgresql-primary:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD: "Qknnkx9rztADh3M3VEtzgXjP4aG3vd5QpBgEjSDXA5LTFR3g9SWxC6mMpvWNxscZj9QfC5FuwTqTMKme7tGmy7FqZ6GWzvzr52j"
    # logging:
    #   driver: "none"
    restart: always
    volumes:
      - /var/lib/postgresql-primary/data:/var/lib/postgresql/data
    networks:
      - postgresql-primary-backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  postgresql-primary-backend:
    external: true
